const productos = [
    { id: 1, nombre: "Café Chiapas – Tueste Claro", imagen: "imagenes/Cafe_Chiapas.png", precio: 160, categoria: "Cafes", descripcion: "Un café suave con una acidez brillante y notas afrutadas de naranja y frutos rojos. Este café de las montañas de Chiapas es perfecto para los que prefieren una taza ligera, con el toque natural de los granos frescos y tostados con suavidad." },
    { id: 2, nombre: "Café Colombia Supremo – Tueste Medio", imagen: "imagenes/Cafe_Colombia.png", precio: 170, categoria: "Cafes", descripcion: "El equilibrio perfecto entre acidez y dulzura, con notas de caramelo y nuez. Este café de las montañas de Colombia es ideal para aquellos que disfrutan de una taza redonda y suave, pero con mucho carácter." },
    { id: 3, nombre: "Café México – Tueste Oscuro", imagen: "imagenes/Cafe_Mexico.png", precio: 190, categoria: "Cafes", descripcion: "Este café de las montañas de México tiene un tueste oscuro que resalta sus notas de cacao amargo, especias y un toque ahumado. Ideal para los amantes de un expreso intenso o café de olla tradicional." },
    { id: 4, nombre: "Café Veracruz", imagen: "imagenes/Cafe_Vera.png", precio: 100, categoria: "Cafes", descripcion: "Delicioso café de Veracruz." },
    { id: 5, nombre: "Café Brasil", imagen: "imagenes/Cafe_Brasil.png", precio: 120, categoria: "Cafes", descripcion: "Delicioso café de grano de Brasil" },
    
    { id: 6, nombre: "Galletas Artesanales", imagen: "imagenes/caja_galletas.png", precio: 200, categoria: "Postres", descripcion: "Galletas recién horneadas con una textura crujiente por fuera y suave por dentro. Perfectas para acompañar tu café o té favorito. Caja de 12 galletas."},
    { id: 7, nombre: "Brownies Clásico de Chocolate", imagen: "imagenes/brownie.png", precio: 50, categoria: "Postres", descripcion: "Brownies intensamente chocolatosos, con una textura densa y húmeda por dentro, y una ligera costra crujiente por fuera perfecto para los amantes del sabor intenso y profundo del chocolate. Hechos con chocolate real y horneados a la perfección." },
    { id: 8, nombre: "Cajas de Trufas Variadas", imagen: "imagenes/caja_trufas.png", precio: 300, categoria: "Postres", descripcion: "Bocaditos irresistibles hechos con ingredientes naturales y sin conservantes. Ideales para disfrutar en cualquier momento o regalar. Caja con 30 piezas. Una selección de nuestras trufas más queridas, con un balance perfecto de sabor y textura." },
    { id: 9, nombre: "Pastel de chocolate", imagen: "imagenes/pastel_choc.png", precio: 150, categoria: "Postres", descripcion: "Prueba el mejor pastel de chocolate." },
    { id: 10, nombre: "Trufas", imagen: "imagenes/trufas.png", precio: 80, categoria: "Postres", descripcion: "Deliciosas trufas." },
    
    { id: 11, nombre: "Cien años de soledad – Gabriel García Márquez", imagen: "imagenes/Cien años de soledad.jpg", precio: 460, categoria: "Libros", descripcion: "Cien años de soledad se ha convertido en la novela más emblemática de la literatura latinoamericana. Escrita por Gabriel García Márquez, esta obra se inscribió en lo que para unos es realismo mágico y para Alejo Carpentier es 'lo real maravilloso'. En un exhaustivo trabajo de imaginación, narra la historia de siete generaciones de la familia Buendía, condenados a la soledad. La novela está estructurada en capítulos sin nombrar. Sin embargo, para facilitar la comprensión del argumento, hemos ordenado y separado el relato en cuatro etapas que identifican, a grandes rasgos, los pasajes más emblemáticos." },
    { id: 12, nombre: "Pedro Páramo – Juan Rulfo", imagen: "imagenes/Pedro_Paramo.jpeg", precio: 270, categoria: "Libros", descripcion: "Pedro Páramo es una novela escrita por el mexicano Juan Rulfo en el año 1955, que se ha convertido en un clásico de la literatura. Se enmarca en un tópico literario universal: el hijo que busca a su padre para reclamar su lugar. Encarna también una realidad propia del mundo latinoamericano del siglo XX: el papel del caciquismo y la violencia en la conformación social. Ambos aspectos no se excluyen sino que se implican, resumen la construcción de un imaginario patriarcal. Pero ¿qué interpretación podemos darle a esta obra? ¿En dónde radica su importancia? ¿Qué la hace una obra de valor universal?" },
    { id: 13, nombre: "Como agua para chocolate – Laura Esquivel", imagen: "imagenes/Como agua para chocolate.png", precio: 330, categoria: "Libros", descripcion: "En el México revolucionario, Tita, la menor de tres hermanas, está condenada a seguir la tradición familiar: no puede casarse y debe cuidar a su madre hasta su muerte. Sin embargo, su amor por Pedro trasciende las reglas impuestas, manifestándose a través de los platillos que cocina con una pasión desbordante. Cada capítulo del libro está ligado a una receta tradicional mexicana, fusionando la comida con las emociones de los personajes." },
    { id: 14, nombre: "Don Quijote de la Mancha - Cervantes", imagen: "imagenes/DQuijote.jpeg", precio: 350, categoria: "Libros", descripcion: "Considerada una de las obras más importantes de la literatura universal, Don Quijote de la Mancha narra las aventuras de Alonso Quijano, un hidalgo que enloquece tras leer demasiados libros de caballería y decide convertirse en caballero andante bajo el nombre de Don Quijote. Junto a su fiel escudero Sancho Panza, vive una serie de peripecias donde la realidad y la fantasía se mezclan constantemente." },
    { id: 15, nombre: "Un mundo feliz - Aldous Huxley", imagen: "imagenes/Mundo_Feliz.jpeg", precio: 150, categoria: "Libros", descripcion: "Un mundo feliz es una novela de ciencia ficción distópica que retrata una sociedad futurista aparentemente perfecta, donde la tecnología y el control social han eliminado el sufrimiento, pero también la libertad individual y las emociones profundas." },
];